# Generated by Django 4.1.4 on 2022-12-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('status_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_guest', models.IntegerField()),
                ('smoking', models.BooleanField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('room_status', models.ManyToManyField(to='rooms.roomstatus')),
                ('roomtype', models.ManyToManyField(to='rooms.roomtype')),
            ],
        ),
    ]
